x-arcane:
  icon: https://github.com/syncthing/syncthing/raw/main/assets/logo-text-128.png
  icon-light: https://github.com/syncthing/syncthing/raw/main/assets/logo-text-128.png
  icon-dark: https://github.com/syncthing/syncthing/raw/main/assets/logo-text-128.png
  urls:
    - https://github.com/xneo1/portainer_templates
  tags:
    - name: sync
      color: gray
    - name: backup
      color: yellow
    - name: cloud
      color: yellow
    - name: tools
      color: blue

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /portainer/Files/AppData/Config/syncthing:/config
      - /portainer:/portainer
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
