x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/cockroachdb.svg
  icon-light: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/cockroachdb.svg
  icon-dark: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/cockroachdb.svg
  urls:
    - https://github.com/mikestraney/portainer-templates
  tags:
    - name: edge
      color: gray

version: '3'

services:
  roach1:
    image: cockroachdb/cockroach:latest
    command: "start --insecure"
    deploy:
      replicas: 1
    ports:
      - 8080

  roachN:
    image: cockroachdb/cockroach:latest
    command: "start --insecure --join=roach1,roachN"
    deploy:
      mode: global
