x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pocketbase.png
  icon-light: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pocketbase.png
  icon-dark: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pocketbase.png
  urls:
    - https://github.com/deployable-sh/stacks
  tags:
    - name: backend-platforms
      color: gray

name: pocketbase

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.39.8
    restart: unless-stopped
    command:
      - serve
      - --http=0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - pbdata:/pb_data

volumes:
  pbdata:
