x-arcane:
  icon: https://raw.githubusercontent.com/xneo1/portainer_templates/master/Images/adguard.png
  icon-light: https://raw.githubusercontent.com/xneo1/portainer_templates/master/Images/adguard.png
  icon-dark: https://raw.githubusercontent.com/xneo1/portainer_templates/master/Images/adguard.png
  urls:
    - https://github.com/xneo1/portainer_templates
  tags:
    - name: adblocking
      color: orange

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /portainer/Files/AppData/Config/adguardhome/workdir:/opt/adguardhome/work
      - /portainer/Files/AppData/Config/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
