x-arcane:
  icon: https://avatars.githubusercontent.com/u/96159884?s=48&v=4
  icon-light: https://avatars.githubusercontent.com/u/96159884?s=48&v=4
  icon-dark: https://avatars.githubusercontent.com/u/96159884?s=48&v=4
  urls:
    - https://github.com/xneo1/portainer_templates
  tags:
    - name: network
      color: gray

services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /portainer/Files/AppData/Config/netalertx/config:/app/config 
      - /portainer/Files/AppData/Config/netalertx/db:/app/db  
    environment:
      - TZ=Europe/Athens      
      - PORT=20211
