x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
  icon-light: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
  icon-dark: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
  urls:
    - https://github.com/deployable-sh/stacks
  tags:
    - name: media
      color: red

name: jellyfin

services:
  jellyfin:
    build: .
    restart: unless-stopped
    environment:
      JELLYFIN_PublishedServerUrl: ${PUBLISHED_SERVER_URL:-http://localhost:5000}
    ports:
      - "5000:5000"
    volumes:
      - config:/config
      - cache:/cache
      - media:/media

volumes:
  config:
  cache:
  media:
