x-arcane:
  icon: https://store-images.s-microsoft.com/image/apps.45485.5f358ea4-e35f-478a-ab92-e85946891f86.b38fbf34-c2b9-4714-9d8a-1232c004df99.4469177b-aba0-4422-ad40-218ff1d967fb
  icon-light: https://store-images.s-microsoft.com/image/apps.45485.5f358ea4-e35f-478a-ab92-e85946891f86.b38fbf34-c2b9-4714-9d8a-1232c004df99.4469177b-aba0-4422-ad40-218ff1d967fb
  icon-dark: https://store-images.s-microsoft.com/image/apps.45485.5f358ea4-e35f-478a-ab92-e85946891f86.b38fbf34-c2b9-4714-9d8a-1232c004df99.4469177b-aba0-4422-ad40-218ff1d967fb
  urls:
    - https://github.com/portainer/templates
  tags:
    - name: edge
      color: gray

services:
  opc-router:
    image: opcrouter/runtime:latest
    restart: unless-stopped
    ports:
      - "49420:49420"
      - "8080:8080"
      - "8081:8081"
    environment:
      - OR_I_ACCEPT_EULA=${OR_I_ACCEPT_EULA}
      - INITIAL_USERNAME=${INITIAL_USERNAME}
      - INITIAL_PASSWORD=${INITIAL_PASSWORD}
    volumes:
      - type: volume
        source: opcrouter-configdb
        target: /data/database
      - type: volume
        source: opcrouter-inray
        target: /inray
      - type: volume
        source: opcrouter-logs
        target: /var/log/opcrouter
volumes:
  opcrouter-configdb:
  opcrouter-inray:
  opcrouter-logs:
