x-arcane:
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/baserow.svg
  icon-light: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/baserow.svg
  icon-dark: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/baserow.svg
  urls:
    - https://github.com/xneo1/portainer_templates
  tags:
    - name: productivity
      color: blue
    - name: development
      color: blue
    - name: no-code
      color: gray

services:
  baserow:
    image: baserow/baserow:latest
    container_name: baserow
    environment:
      - TZ=Europe/Athens
    volumes:
      - /portainer/Files/AppData/Config/baserow:/baserow/data
    ports:
      - 280:80  #changed from default 80
      - 2443:443
    restart: unless-stopped
