x-arcane:
  icon: https://pbs.twimg.com/profile_images/1658849767865167876/hA5OXD9m_400x400.jpg
  icon-light: https://pbs.twimg.com/profile_images/1658849767865167876/hA5OXD9m_400x400.jpg
  icon-dark: https://pbs.twimg.com/profile_images/1658849767865167876/hA5OXD9m_400x400.jpg
  urls:
    - https://github.com/portainer/templates
  tags:
    - name: edge
      color: gray

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb-poc
    restart: always
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/home/postgres/pgdata
    environment:
      - POSTGRES_PASSWORD=${pgpassword}

volumes:
  timescaledb-data:
